/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as UniversitiesRouteImport } from './routes/universities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/essay': typeof EssayRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/essay': typeof EssayRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/essay': typeof EssayRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assessment' | '/essay' | '/scholarships' | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assessment' | '/essay' | '/scholarships' | '/universities'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/essay'
    | '/scholarships'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  EssayRoute: typeof EssayRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  EssayRoute: EssayRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
